CREATE DATABASE IF NOT EXISTS fog_security;
USE fog_security;

CREATE TABLE IF NOT EXISTS ant_table (
  id INT AUTO_INCREMENT PRIMARY KEY,
  node_mac VARCHAR(32) NOT NULL,
  mac_hash CHAR(64) NOT NULL UNIQUE,
  status ENUM('Trusted','Banned') NOT NULL DEFAULT 'Trusted',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS routing_table (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(64) NOT NULL UNIQUE,
  current_node VARCHAR(64) NOT NULL,
  session_state JSON NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS telemetry (
  id INT AUTO_INCREMENT PRIMARY KEY,
  node_id VARCHAR(64) NOT NULL,
  auth_fail_rate FLOAT DEFAULT 0,
  latency_ms INT DEFAULT 0,
  error_rate FLOAT DEFAULT 0,
  handoff_rate FLOAT DEFAULT 0,
  cpu INT DEFAULT 0,
  mem INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
